// app/components/Experience/Experience.vue
<template>
  <section class="section" data-testid="experience-section">
    <UContainer>
      <SectionTitle
        id="work-experience"
        accent
        :label="t('cv.workExperience')"
      />
      <UCard data-testid="experience-card">
        <div class="experience-list" role="list" data-testid="experience-list">
          <article
            v-for="(job, idx) in experiences"
            :key="job.description.en"
            class="job-item"
            role="listitem"
            itemscope
            itemtype="https://schema.org/JobPosting"
            :data-testid="`experience-item-${idx}`"
          >
            <div class="job-content">
              <header class="job-header">
                <h3
                  class="heading-3"
                  itemprop="title"
                  :data-testid="`experience-item-title-${idx}`"
                >
                  {{ job.title[lang] }}
                </h3>
                <div class="job-meta">
                  <span class="meta-text">
                    <time :datetime="toDateTime(job.from)" itemprop="datePosted">{{
                      formatPeriod(job.from, job.end)
                    }}</time>
                    <span class="meta-separator">|</span>
                    <span
                      itemprop="hiringOrganization"
                      itemscope
                      itemtype="https://schema.org/Organization"
                    >
                      <InlineLink
                        v-if="job.company.link"
                        :href="job.company.link"
                        class="company-link"
                        itemprop="url"
                      >
                        <span itemprop="name">{{ job.company.name }}</span>
                      </InlineLink>
                      <span v-else itemprop="name">{{ job.company.name }}</span>
                    </span>
                    <template v-if="job.employmentType">
                      <span class="meta-separator">|</span>
                      <span
                        itemprop="jobLocation"
                        itemscope
                        itemtype="https://schema.org/Place"
                      >
                        <span itemprop="addressLocality">{{
                          t(`experience.employmentType.${job.employmentType}`)
                        }}</span>
                      </span>
                    </template>
                    <span class="meta-separator">|</span>
                    <span
                      itemprop="jobLocation"
                      itemscope
                      itemtype="https://schema.org/Place"
                    >
                      <span itemprop="addressLocality">{{ job.location }}</span>
                    </span>
                  </span>
                </div>
              </header>
              <div
                v-if="job.description"
                class="description"
                itemprop="description"
              >
                <p>
                  {{ job.description[lang] }}
                </p>
              </div>
              <div class="technologies">
                <span class="tech-label">{{
                  t('experience.technologies')
                }}</span>
                <ul
                  class="tech-list"
                  role="list"
                  :data-testid="`experience-item-tech-list-${idx}`"
                >
                  <li
                    v-for="tech in job.technologies"
                    :key="tech.name"
                    class="tech-item"
                    role="listitem"
                  >
                    <span class="skill" itemprop="skill">
                      <InlineLink v-if="tech.link" :href="tech.link">{{
                        tech.name
                      }}</InlineLink>
                      <template v-else>
                        {{ tech.name }}
                      </template>
                    </span>
                  </li>
                </ul>
              </div>
            </div>
            <hr v-if="idx < experiences.length - 1" class="job-divider" >
          </article>
        </div>
      </UCard>
    </UContainer>
  </section>
</template>

<script setup lang="ts">
import './Experience.scss';
import type { CVSupportedLangs, WorkExperience } from '~/types/cv';
import InlineLink from '../ui/InlineLink.vue';
import SectionTitle from '../ui/SectionTitle.vue';
import {
  formatPeriod as formatPeriodRange,
  toDateTime,
} from '~/utils/period';

const { t } = useI18n();

defineProps<{
  experiences: WorkExperience[];
  lang: CVSupportedLangs;
}>();

const formatPeriod = (
  from: WorkExperience['from'],
  end?: WorkExperience['end'],
) => formatPeriodRange(from, end, t('experience.present'));
</script>

// components/experience.tsx
import { Badge } from '@/components/ui/badge';
import { InlineLink } from '@/components/ui/inline-link';
import { SectionTitle } from '@/components/ui/section-title';
import type { Locale, WorkExperience } from '@/lib/cv/types';
import { uiMessages } from '@/lib/ui-messages';
import { formatPeriod, toDateTime } from '@/lib/period';

type ExperienceProps = {
  experiences: WorkExperience[];
  locale: Locale;
};

function MetaSeparator() {
  return <span className="hidden text-border sm:inline" aria-hidden="true">·</span>;
}

export function Experience({ experiences, locale }: ExperienceProps) {
  const messages = uiMessages(locale);
  const presentLabel = messages.experience.present;
  const technologiesLabel = messages.experience.technologies;
  const employmentTypeLabels = messages.experience.employmentType;

  return (
    <section data-testid="experience-section">
      <SectionTitle
        id="work-experience"
        accent
        label={messages.cv.workExperience}
      />
      <div data-testid="experience-card">
        <div role="list" data-testid="experience-list">
          {experiences.map((job, idx) => (
            <article
              key={`${job.company.name}-${job.from.year}-${idx}`}
              className="cv-entry print:break-inside-avoid"
              role="listitem"
              itemScope
              itemType="https://schema.org/JobPosting"
              data-testid={`experience-item-${idx}`}
            >
              <header className="space-y-2.5 text-center sm:space-y-3">
                <h3
                  className="text-lg font-semibold text-foreground sm:text-xl"
                  itemProp="title"
                  data-testid={`experience-item-title-${idx}`}
                >
                  {job.title[locale]}
                </h3>
                <div className="cv-meta">
                  <time dateTime={toDateTime(job.from)} itemProp="datePosted">
                    {formatPeriod(job.from, job.end, presentLabel)}
                  </time>
                  <MetaSeparator />
                  <span
                    itemProp="hiringOrganization"
                    itemScope
                    itemType="https://schema.org/Organization"
                  >
                    {job.company.link ? (
                      <InlineLink href={job.company.link} itemProp="url">
                        <strong itemProp="name">{job.company.name}</strong>
                      </InlineLink>
                    ) : (
                      <strong itemProp="name">{job.company.name}</strong>
                    )}
                  </span>
                  {job.employmentType ? (
                    <>
                      <MetaSeparator />
                      <span>
                        {
                          employmentTypeLabels[
                            job.employmentType as keyof typeof employmentTypeLabels
                          ]
                        }
                      </span>
                    </>
                  ) : null}
                  <MetaSeparator />
                  <span
                    itemProp="jobLocation"
                    itemScope
                    itemType="https://schema.org/Place"
                  >
                    <span itemProp="addressLocality">{job.location}</span>
                  </span>
                </div>
              </header>

              <div
                className="cv-body text-center sm:text-left"
                itemProp="description"
              >
                <p>{job.description[locale]}</p>
              </div>

              <div>
                <p className="cv-label text-center">{technologiesLabel}</p>
                <ul
                  className="flex flex-wrap justify-center gap-2"
                  role="list"
                  data-testid={`experience-item-tech-list-${idx}`}
                >
                  {job.technologies.map((tech) => (
                    <li key={tech.name} role="listitem">
                      <Badge
                        variant="outline"
                        className="justify-center border-border/80 bg-secondary/50 px-2.5 py-1 text-center text-xs font-normal text-secondary-foreground"
                        asChild={!!tech.link}
                      >
                        {tech.link ? (
                          <a href={tech.link} target="_blank" rel="noopener">
                            <span itemProp="skill">{tech.name}</span>
                          </a>
                        ) : (
                          <span itemProp="skill">{tech.name}</span>
                        )}
                      </Badge>
                    </li>
                  ))}
                </ul>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
