// components/Experience/Experience.vue
<template>
  <section class="section">
    <UContainer>
      <h2 class="section-title" id="work-experience">
        <a href="#work-experience"># Work Experience</a>
      </h2>
      <UCard class="cv-card">
        <div class="experience-list">
          <div v-for="(job, idx) in experiences" :key="job.title" class="job-item">
            <div class="job-content">
              <div class="job-header">
                <h3 class="heading-3">{{ job.title }}</h3>
                <div class="job-meta">
                  <span class="meta-text">
                    {{ formatPeriod(job.from, job.end) }}
                    <span class="meta-separator">|</span>
                    <a v-if="job.companyUrl" :href="job.companyUrl" target="_blank" rel="noopener" class="company-link">{{ job.company }}</a>
                    <template v-else>{{ job.company }}</template>
                    <span class="meta-separator">|</span>
                    {{ job.location }}
                  </span>
                </div>
              </div>
              <p v-if="job.description" class="description">
                {{ job.description }}
              </p>
              <div class="technologies">
                <span class="tech-label">Technologies</span>
                <ul class="tech-list">
                  <li v-for="tech in job.technologies" :key="tech" class="tech-item">
                    {{ tech }}
                  </li>
                </ul>
              </div>
            </div>
            <hr v-if="idx < experiences.length - 1" class="job-divider" />
          </div>
        </div>
      </UCard>
    </UContainer>
  </section>
</template>

<script setup lang="ts">
import './Experience.scss';
import type { WorkExperience } from '~/types/cv';

defineProps<{
  experiences: WorkExperience[];
}>();

const formatPeriod = (from: string, end?: string) => {
  return end ? `${from} - ${end}` : `${from} - Present`;
};
</script>

<style lang="scss" scoped>
.job-meta {
  margin-top: 0.5rem;
}

.meta-text {
  color: var(--color-gray-500);
  font-size: 0.875rem;
}

.meta-separator {
  margin: 0 0.5rem;
  color: var(--color-gray-400);
}

.company-link {
  color: inherit;
  text-decoration: none;
  transition: color 0.2s ease;

  &:hover {
    color: var(--color-primary);
  }
}
</style>

// components/experience.tsx
import { Badge } from '@/components/ui/badge';
import { InlineLink } from '@/components/ui/inline-link';
import { SectionTitle } from '@/components/ui/section-title';
import type { Locale, WorkExperience } from '@/lib/cv/types';
import { uiMessages } from '@/lib/ui-messages';
import { formatPeriod, toDateTime } from '@/lib/period';

type ExperienceProps = {
  experiences: WorkExperience[];
  locale: Locale;
};

function MetaSeparator() {
  return <span className="hidden text-border sm:inline" aria-hidden="true">·</span>;
}

export function Experience({ experiences, locale }: ExperienceProps) {
  const messages = uiMessages(locale);
  const presentLabel = messages.experience.present;
  const technologiesLabel = messages.experience.technologies;
  const employmentTypeLabels = messages.experience.employmentType;

  return (
    <section data-testid="experience-section">
      <SectionTitle
        id="work-experience"
        accent
        label={messages.cv.workExperience}
      />
      <div data-testid="experience-card">
        <div role="list" data-testid="experience-list">
          {experiences.map((job, idx) => (
            <article
              key={`${job.company.name}-${job.from.year}-${idx}`}
              className="cv-entry print:break-inside-avoid"
              role="listitem"
              itemScope
              itemType="https://schema.org/JobPosting"
              data-testid={`experience-item-${idx}`}
            >
              <header className="space-y-2.5 text-center sm:space-y-3">
                <h3
                  className="text-lg font-semibold text-foreground sm:text-xl"
                  itemProp="title"
                  data-testid={`experience-item-title-${idx}`}
                >
                  {job.title[locale]}
                </h3>
                <div className="cv-meta">
                  <time dateTime={toDateTime(job.from)} itemProp="datePosted">
                    {formatPeriod(job.from, job.end, presentLabel)}
                  </time>
                  <MetaSeparator />
                  <span
                    itemProp="hiringOrganization"
                    itemScope
                    itemType="https://schema.org/Organization"
                  >
                    {job.company.link ? (
                      <InlineLink href={job.company.link} itemProp="url">
                        <strong itemProp="name">{job.company.name}</strong>
                      </InlineLink>
                    ) : (
                      <strong itemProp="name">{job.company.name}</strong>
                    )}
                  </span>
                  {job.employmentType ? (
                    <>
                      <MetaSeparator />
                      <span>
                        {
                          employmentTypeLabels[
                            job.employmentType as keyof typeof employmentTypeLabels
                          ]
                        }
                      </span>
                    </>
                  ) : null}
                  <MetaSeparator />
                  <span
                    itemProp="jobLocation"
                    itemScope
                    itemType="https://schema.org/Place"
                  >
                    <span itemProp="addressLocality">{job.location}</span>
                  </span>
                </div>
              </header>

              <div
                className="cv-body text-center sm:text-left"
                itemProp="description"
              >
                <p>{job.description[locale]}</p>
              </div>

              <div>
                <p className="cv-label text-center">{technologiesLabel}</p>
                <ul
                  className="flex flex-wrap justify-center gap-2"
                  role="list"
                  data-testid={`experience-item-tech-list-${idx}`}
                >
                  {job.technologies.map((tech) => (
                    <li key={tech.name} role="listitem">
                      <Badge
                        variant="outline"
                        className="justify-center border-border/80 bg-secondary/50 px-2.5 py-1 text-center text-xs font-normal text-secondary-foreground"
                        asChild={!!tech.link}
                      >
                        {tech.link ? (
                          <a href={tech.link} target="_blank" rel="noopener">
                            <span itemProp="skill">{tech.name}</span>
                          </a>
                        ) : (
                          <span itemProp="skill">{tech.name}</span>
                        )}
                      </Badge>
                    </li>
                  ))}
                </ul>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
